### ISSUE TITLE
SecurityError when previewing under Mac OS 10.11

### ISSUE THREAD

**Issue by xunker** [matiasinsaurralde/atom-scad-preview#1]
Max OS 10.11.4
Atom 1.7.4
atom-scad-preview 0.0.3 (from package installer)

---

When I try to preview some scad code, I get the following error message popup:

```
SecurityError: Failed to construct 'Worker': Access to the script at 'blob:file%3A///a4e2f29b-bd8f-4f1b-9a5d-1834982fd51a' is denied by the document's Content Security Policy.
111

(file:///Users/my_user_name/.atom/packages/atom-scad-preview/standalone/openjscad.js line 512)
```

The code I am trying to prevew in this example is:

``` openscad
cube([10,10,10]);
```

..but it happens on any code regardless.

Just in case you need it, here is a stack trace from the developer panel:

```
index.js:52 Window load time: 604ms
/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:983 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
/Users/my_user_name/.atom/packages/atom-scad-preview/lib/atom-scad-preview.js:89 AtomScadPreview was toggled!
/Users/my_user_name/.atom/packages/atom-scad-preview/lib/atom-scad-preview-view.js:27 file:///Users/my_user_name/.atom/packages/atom-scad-preview/standalone/three.min.js
/Users/my_user_name/.atom/packages/atom-scad-preview/lib/atom-scad-preview-view.js:27 file:///Users/my_user_name/.atom/packages/atom-scad-preview/standalone/orbitcontrols.js
/Users/my_user_name/.atom/packages/atom-scad-preview/lib/atom-scad-preview-view.js:27 file:///Users/my_user_name/.atom/packages/atom-scad-preview/standalone/projector.js
/Users/my_user_name/.atom/packages/atom-scad-preview/lib/atom-scad-preview-view.js:27 file:///Users/my_user_name/.atom/packages/atom-scad-preview/standalone/canvasrenderer.js
/Users/my_user_name/.atom/packages/atom-scad-preview/lib/atom-scad-preview-view.js:27 file:///Users/my_user_name/.atom/packages/atom-scad-preview/standalone/jquery-2.1.3.min.js
/Users/my_user_name/.atom/packages/atom-scad-preview/lib/atom-scad-preview-view.js:27 file:///Users/my_user_name/.atom/packages/atom-scad-preview/standalone/csg.js
/Users/my_user_name/.atom/packages/atom-scad-preview/lib/atom-scad-preview-view.js:27 file:///Users/my_user_name/.atom/packages/atom-scad-preview/standalone/threecsg.js
/Users/my_user_name/.atom/packages/atom-scad-preview/lib/atom-scad-preview-view.js:27 file:///Users/my_user_name/.atom/packages/atom-scad-preview/standalone/openjscad.js
/Users/my_user_name/.atom/packages/atom-scad-preview/lib/atom-scad-preview-view.js:27 file:///Users/my_user_name/.atom/packages/atom-scad-preview/standalone/formats.js
/Users/my_user_name/.atom/packages/atom-scad-preview/lib/atom-scad-preview-view.js:27 file:///Users/my_user_name/.atom/packages/atom-scad-preview/standalone/main.js
/Users/my_user_name/.atom/packages/atom-scad-preview/lib/atom-scad-preview.js:95 container => AtomScadPreviewView {pathname: "/Users/my_user_name/tmp/rolly.scad", fileIdentifier: "d8da61eeb08cc5aa9be1061eef2266a8", element: div.atom-scad-preview, lastOpened: 1464710406910}element: div.atom-scad-previewfileIdentifier: "d8da61eeb08cc5aa9be1061eef2266a8"lastOpened: 1464710406910pathname: "/Users/my_user_name/tmp/rolly.scad"render: ()__proto__: AtomScadPreviewView
three.min.js:513 THREE.WebGLRenderer 70
openjscad.js:477 baselibraries ["file:///Users/my_user_name/.atom/packages/atom-scad-preview/standalone/csg.js", "file:///Users/my_user_name/.atom/packages/atom-scad-preview/standalone/openjscad.js"]
openjscad.js:512 Refused to create a child context containing 'blob:file%3A///a4e2f29b-bd8f-4f1b-9a5d-1834982fd51a' because it violates the following Content Security Policy directive: "default-src *". Note that 'child-src' was not explicitly set, so 'default-src' is used as a fallback.
OpenJsCad.parseJsCadScriptASync @ openjscad.js:512OpenJsCad.Processor.rebuildSolid @ openjscad.js:1083OpenJsCad.Processor.setJsCad @ openjscad.js:1012(anonymous function) @ main.js:14
openjscad.js:512 Uncaught SecurityError: Failed to construct 'Worker': Access to the script at 'blob:file%3A///a4e2f29b-bd8f-4f1b-9a5d-1834982fd51a' is denied by the document's Content Security Policy.OpenJsCad.parseJsCadScriptASync @ openjscad.js:512OpenJsCad.Processor.rebuildSolid @ openjscad.js:1083OpenJsCad.Processor.setJsCad @ openjscad.js:1012(anonymous function) @ main.js:14
/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:622 Error serializing package 'atom-scad-preview' TypeError: Cannot read property 'serialize' of null
    at Object.module.exports.AtomScadPreview.serialize (/Users/my_user_name/.atom/packages/atom-scad-preview/lib/atom-scad-preview.js:85:57)
    at Package.module.exports.Package.serialize (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:619:100)
    at PackageManager.module.exports.PackageManager.serializePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:596:63)
    at PackageManager.module.exports.PackageManager.serialize (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:589:14)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:771:38)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:984:27module.exports.Package.serialize @ /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:622module.exports.PackageManager.serializePackage @ /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:596module.exports.PackageManager.serialize @ /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:589module.exports.AtomEnvironment.serialize @ /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:771(anonymous function) @ /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:984
```

**Comment by matiasinsaurralde** [comment]
Let me research this!

**Comment by cyberkeiler** [comment]
Same error here with Mac OS X 10.11.**5**, Atom 1.7.4 and atom-scad-preview (alpha?) 0.0.3

**Comment by matiasinsaurralde** [comment]
Hi guys, can you try the newest version? It's 0.1.0
https://atom.io/packages/atom-scad-preview

**Comment by xunker** [comment]
@matiasinsaurralde Tried under 10.11.4, but using Atom 1.8.0. Got the same error as #3 .

**Comment by matiasinsaurralde** [comment]
Ah I see, this is related to the Openjscad dialect that uses CSG:
Can you try the following code?
```
function main() {
  return CSG.roundedCube({radius: 10, roundradius: 1})
}
```

**Comment by apla** [comment]
Seems like this issue is resolved
