### ISSUE TITLE
Failed to activate the atom-scad-preview package

### ISSUE THREAD

**Issue by Gasman2014** [matiasinsaurralde/atom-scad-preview#4]
Opening a project and building (either with menu item or cmd+Y) results in an error 
'Cannot find module 'loophole'

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [atom-scad-preview](https://github.com/matiasinsaurralde/atom-scad-preview) package, v0.3.0
### Stack Trace

Failed to activate the atom-scad-preview package

```
At Cannot find module 'loophole'

Error: Cannot find module 'loophole'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/johnpateman/.atom/packages/atom-scad-preview/lib/atom-scad-preview-view.js:6:14)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/johnpateman/.atom/packages/atom-scad-preview/lib/atom-scad-preview.js:4:27)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:795:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:01.0 atom-scad-preview:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "mcduino",
      "build-tools",
      "r-exec",
      "language-matlab-octave",
      "git-time-machine",
      "highlight-column",
      "imdone-atom",
      "g-code"
    ],
    "projectHome": "/Users/johnpateman/Documents/Code/",
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Repl, v0.5.0
atom-scad-preview, v0.3.0
auto-update-packages, v1.0.1
autocomplete-clang, v0.9.3
build, v0.64.0
build-make, v0.10.0
build-xcodebuild, v0.2.0
busy, v0.5.0
file-icons, v1.7.15
highlight-selected, v0.11.2
ink, v0.4.4
julia-client, v0.4.7
language-arduino, v0.4.1
language-gherkin, v1.0.4
language-ini, v1.16.0
language-julia, v0.6.0
language-linuxcnc-gcode, v0.1.0
language-mathematica, v0.2.1
language-openscad, v0.4.3
language-r, v0.4.1
latex-completions, v0.3.1
linter, v1.11.14
linter-gcc, v0.6.14
linter-lintr, v1.0.4
linter-matlab, v1.1.0
minimap, v4.24.6
platformio-ide, v1.2.2
platformio-ide-terminal, v2.1.0
project-manager, v2.9.7
tool-bar, v0.4.0
uber-juno, v0.1.1

# Dev
No dev packages
```

**Comment by apla** [comment]
v0.4.0 just landed to fix this

**Comment by apla** [comment]
Seems like issue fixed
